name: Validation Project
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
        - name: Get Code
          uses: actions/checkout@v4
        - name: NodeJs Setup
          uses: actions/setup-node@v4
          with:
            node-version: 20
        - name: Setup Dependencies
          run: npm ci
        - name: Run Lint
          run: npm run lint